return {
    "tpope/vim-fugitive",
    cmd = { "Git", "Gdiffsplit", "Gread", "Gwrite", "GBrowse" },
    keys = {
        { "<leader>Gs", "<cmd>Git<CR>", desc = "Git Status" },
        { "<leader>Gc", "<cmd>Git commit<CR>", desc = "Git Commit" },
        { "<leader>Gp", "<cmd>Git push<CR>", desc = "Git Push" },
        { "<leader>Gl", "<cmd>Git pull<CR>", desc = "Git Pull" },
        { "<leader>GL", "<cmd>Git log<CR>", desc = "Git Log" },
        { "<leader>Go", "<cmd>Git log --oneline --decorate --graph<CR>", desc = "Git Log Graph" },
        { "<leader>Gd", "<cmd>Git diff<CR>", desc = "Git Diff" },
        { "<leader>GD", "<cmd>Gdiffsplit<CR>", desc = "Git Diff Split" },
        { "<leader>Gb", "<cmd>Git blame<CR>", desc = "Git Blame" },
        { "<leader>GC", ":Git checkout ", desc = "Git Checkout" },
        { "<leader>Gr", "<cmd>Gread<CR>", desc = "Git Read" },
        { "<leader>GR", "<cmd>Git reset --soft HEAD~1<CR>", desc = "Git Reset Soft" },
        { "<leader>Gw", "<cmd>GBrowse<CR>", desc = "Git Browse" },
        { "<leader>Gh", "<cmd>Gitsigns stage_hunk<CR>", desc = "Stage Hunk" },
        { "<leader>Ga", "<cmd>Git add %<CR>", desc = "Git Add File" },
        { "<leader>GA", "<cmd>Git add .<CR>", desc = "Git Add All" },
        { "<leader>Gu", "<cmd>Git restore --staged %<CR>", desc = "Git Unstage File" },
        { "<leader>GU", "<cmd>Git restore --staged .<CR>", desc = "Git Unstage All" },
    },
}
